// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

const _Token_name = "INVALIDEOFCOMMENTIDENTIFIERINTEGERPLUSMINUSMULTIPLYDIVIDEMODULOANDOREQUALSLESS_THANGREATER_THANISNOTNOT_EQUALSLESS_THAN_EQUALSGREATER_THAN_EQUALSCOMMASEMICOLONCOLONROUND_BRACKET_OPENROUND_BRACKET_CLOSECURLY_BRACKET_OPENCURLY_BRACKET_CLOSESQUARE_BRACKET_OPENSQUARE_BRACKET_CLOSEEMPTY_LISTIFELSEWHILERETURN"

var _Token_index = [...]uint16{0, 7, 10, 17, 27, 34, 38, 43, 51, 57, 63, 66, 68, 74, 83, 95, 97, 100, 110, 126, 145, 150, 159, 164, 182, 201, 219, 238, 257, 277, 287, 289, 293, 298, 304}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
